### ISSUE TITLE
报E_STRICT错WeixinWebProvider.php：getCodeFields

### ISSUE THREAD

**Issue by CallMeNP** [liaol/socialite-cn#6]
WeixinWebProvider里getCodeFields的参数没有默认值。
WeixinWebProvider 继承了 AbstractProvider，
而在AbstractProvider中，是这么定义的：function getCodeFields($state = null)。所以会报错。

希望可以修改，然后发一个新version tag，我们好更新。
（在我们的项目中，为保障代码稳定，规定了使用指明version的方式，而不是dev-master）

非常感谢您所做的工作，对我们的项目非常有帮助。

**Comment by liaol** [comment]
谢谢反馈。
你可以发个pr来fix bug
我现在手头没有相关的开发者账号，不方便调试。

tag后来觉得没什么用，功能单一，你需要的话等我合并后加上。

**Comment by liaol** [comment]
已更新tag
